[project]
name = "staticsite"
version = "0.1.0"
description = "Static Site Generator from md -> html"
readme = "README.md"
authors = [
    { name = "danl1k3", email = "like.danyt@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
staticsite = "staticsite:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
